CREATE TABLE IF NOT EXISTS short_links (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  clicks BIGINT DEFAULT 0,
  last_clicked TIMESTAMP WITH TIME ZONE NULL,
  deleted BOOLEAN DEFAULT FALSE
);
